### ISSUE TITLE
APC terminals visible after restart

### ISSUE THREAD

**Issue by LightAnarchy** [Chryseus/Persistent-Bay#14] opened 2018-11-23 03:16 UTC
#### Description of issue

After the restart, the APC terminals are now above the floor tiles, even though they should be under.

#### Difference between expected and actual behavior

APC terminals should be hidden under the floor.

#### Steps to reproduce 

Restart I think and check APCs?

#### Specific information for locating

Don't have anything here right now.

#### Length of time in which bug has been known to occur

Since the restart just now.

#### Client version, Server revision & Game ID

Server Revision: bed3b7245387899f3c990c9473e62f7485826866 - newmap - 2018-11-23
Game ID: bXt-aA6H

#### Issue bingo

Please check whatever applies. More checkboxes checked increase your chances of the issue being looked at sooner.

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced after a restart
- [X] Issue happened recently (less than 7 days ago)
- [X] [Couldn't find an existing issue about this](https://github.com/Persistent-SS13/Persistent-Bay/issues)

**Comment by Chryseus** [comment] 2018-11-23 14:23
Problem seems to be caused by the turf plane variable being set to PLATING_PLANE rather than the correct TURF_PLANE, will need to see if it can be consistently reproduced.

**Comment by Chryseus** [comment] 2018-11-27 16:26
related to #23

**Comment by Chryseus** [comment] 2018-11-27 22:18
Likely fixed in cef2913045a2806c73b1591a4842871fd94fc031

**Closed as completed by Chryseus** 2018-11-27 22:18 UTC
Labels: bug, medium priority
